### ISSUE TITLE
Apparent unexpected difference in results when re-using a binary Network file

### ISSUE THREAD

**Issue by bwynneHEP** [mrc-ide/covid-sim#116]
This is posted from the UK RAMP “RED TEAM” at Edinburgh University, as invited through UKRI and RAMP with agreement of Microsoft. We have taken the charge of kicking the tires on the code as a pseudo public user. We are testing documentation, stability and usability based upon the documentation we can find on the git repository. Thus, if we report something that is “well known” then it is in effect a report on the lack of documentation which would have made this clear.

**Issue: Apparent unexpected difference in results when re-using a binary Network file**

The expected mode of operation for the covid-sim package seems to be a single run with nominal conditions, followed by subsequent runs with variations to parameters: this is logical.

Time-saving measures are implemented by allowing the nominal run to save binary representations of the population density and network data. These files can be loaded and re-used in subsequent runs, rather than being re-created each time (using the /S: and /L: command line arguments)

However, there appears to be a bug in either the creation or re-use of the network file. If we attempt two completely identical runs, only varying in that the second should use the network file produced by the first, the results are quite different:

![NetworkReuse](https://user-images.githubusercontent.com/63859253/79884299-e5413d80-83ec-11ea-847f-b20eb248c0a9.png)

This mostly manifests as a time-offset, but there are numerical changes beyond that.

Re-use of the binary population density file seems to have no associated problems.

**Comment by RankingMrP** [comment]
Wow. This is astonishing. The whole world was shut down because of this amateur piece of code? This is quackery!

**Comment by nhamwey** [comment]
> Wow. This is astonishing. The whole world was shut down because of this amateur piece of code? This is quackery!

Did you join github to troll?
