### ISSUE TITLE
Modularise

### ISSUE THREAD

**Issue by mosanden** [mrc-ide/covid-sim#162]
Please split the code into modules so anyone can read it in a reasonable time.

**Comment by weshinsley** [comment]
Feel free to suggest where we should do so by creating a more specific issue. The recent refactoring work with Microsoft and Github have split the code into files that are much more readable than before, but it is very unrealistic to expect "anyone to read it in a reasonable time".

It will require some time and effort; others have managed that and submitted issues in such a way that we can interact with them and discuss specific issues.
