### ISSUE TITLE
Document PRNG references

### ISSUE THREAD

**Issue by cjgdev** [mrc-ide/covid-sim#167]
I’m exploring the random number generator as a possible runtime performance optimisation candidate. Could a maintainer please disclose the paper / algorithm implemented by ranf / ranf_mt, so that I can be satisfied that any substitute PRNG is equivalent?

**Comment by weshinsley** [comment]
See RANLIB in the readme an open-source dependency we've used.
https://people.sc.fsu.edu/~jburkardt/c_src/ranlib/ranlib.html

**Comment by mikehearn** [comment]
It's this one: https://dl.acm.org/doi/10.1145/62959.62969

**Comment by cjgdev** [comment]
Thanks @mikehearn that’s precisely what I was looking for.

**Comment by weshinsley** [comment]
Thanks both, and sorry I closed this one a bit abruptly... one of those days, it has been.

**Comment by cjgdev** [comment]
@weshinsley no need to apologise
