### ISSUE TITLE
Possible bug in Fisher-Yates shuffle

### ISSUE THREAD

**Issue by jtkeeling** [mrc-ide/covid-sim#168]
On line 1875 of SetupModel.cpp, it appears there might be a bug in the Fisher-Yates shuffle code.

The current code is:
```
for (int index1 = cnt - 1; index1 > 0; index1--)
	{
		int index2 = (int)(((double)k) * ranf());
		int tmp = PeopleArray[index1];
		PeopleArray[index1] = PeopleArray[index2];
		PeopleArray[index2] = tmp;
	}
```

`k` on the first line of the body of the loop appears to refer to some unrelated value above. I believe it should be replaced by `(index1 + 1)`, in order for `index2` to be in the range [0, `index1`].

**Comment by jtkeeling** [comment]
In particular, refer to the pseudocode in the first codeblock in this section of the Wikipedia article: https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle#The_modern_algorithm

**Comment by MichalPaszkiewicz** [comment]
Yes, seems k is being incremented previously for some for loops, then has been added here erroneously, probably due to the fact that k is often used as the random number name, as in step 2 on wiki: https://en.m.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle

**Comment by weshinsley** [comment]
Well spotted and thank you for reporting this.
