### ISSUE TITLE
Archive this project and start again

### ISSUE THREAD

**Issue by MrHash** [mrc-ide/covid-sim#174]
This embarrassing legacy BBOM code has repeatedly failed to even remotely predict any real world outcomes over many years, and is chiefly responsible for actions taken to disrupt the lives of billions of people. There is no sense in trying to refactor this other than for academic reasons, and no further predictions from this code base should ever be taken seriously again.

**Comment by Xaeroxe** [comment]
This is a low-quality drive-by comment filled with vitrol. if you're going to make strong claims like that you need specific citations, but I suspect you're not really interested in providing them.
