### ISSUE TITLE
BUG: Incorrect Results from Model

### ISSUE THREAD

**Issue by beewenib** [mrc-ide/covid-sim#175]
This bug is on the original source code. Since it's not available, I'll log it here on the new repo. Note that I didn't see this logged anywhere.

Steps to Reproduce
1. Enter various inputs for R0 and other factors
**Result:** Prediction of over 1M deaths in the US, 500k in the UK

Bug:
The actual results are very different. Several months later (May 7, 2020), [per CDC data in the US](https://www.cdc.gov/nchs/nvss/vsrr/covid19/index.htm), only 47k deaths. Keep in mind though that this includes seasonal flu and pnumonia. 

Maybe it's the result of the memory leaks that some of the professional C++ devs are pointing out?  I've seen some references to multi-threading issues. Anyhow, this for sure needs to be fixed as the results from the model and the actual values are much much different.

**Comment by insidedctm** [comment]
You're having a laugh, right? Stop wasting people's time.

**Comment by OscarVanL** [comment]
Have you tried turning it off and on again?

**Comment by beewenib** [comment]
> You're having a laugh, right? Stop wasting people's time.

No. This is a serious bug that needs to be fixed. Whether it's in the model source code, the UI that resulted in bad values, etc. Not sure, but this is a bug that needs to be fixed.

**Comment by insidedctm** [comment]
> > You're having a laugh, right? Stop wasting people's time.
> 
> No. This is a serious bug that needs to be fixed. Whether it's in the model source code, the UI that resulted in bad values, etc. Not sure, but this is a bug that needs to be fixed.

Seeing as you've just joined GitHub maybe you are not familiar with how open source works. If you find a specific issue then raise an issue explaining why you think it's a problem, possibly suggest a fix. Even better submit a PR.

**Comment by beewenib** [comment]
> > > You're having a laugh, right? Stop wasting people's time.
> > 
> > 
> > No. This is a serious bug that needs to be fixed. Whether it's in the model source code, the UI that resulted in bad values, etc. Not sure, but this is a bug that needs to be fixed.
> 
> Seeing as you've just joined GitHub maybe you are not familiar with how open source works. If you find a specific issue then raise an issue explaining why you think it's a problem, possibly suggest a fix. Even better submit a PR.

I'm a software tester, so I'm just reporting a defect here. The job of a software tester is to report defects.

**Comment by insidedctm** [comment]
So as a first start log the various runs and parameters you used and the output you got.

**Comment by beewenib** [comment]
> So as a first start log the various runs and parameters you used and the output you got.

Will do. It would be helpful to have the original model also, so that we can compare.

**Comment by insidedctm** [comment]
I suggest you run it on this version first. As a general principle putting in the effort yourself first is the way to win appreciation and effort from other people.

**Comment by beewenib** [comment]
> I suggest you run it on this version first. As a general principle putting in the effort yourself first is the way to win appreciation and effort from other people.

Will do. Until then, you should have plenty of data to see that this is a bug. All of the news sources show that your model predicted a value that is several thousand times higher than actuals (see the original bug here also). Maybe check with the original Epidemiologist that is in the news? He can probably give you the values, or even better, please have him publish them here so that they can be peer reviewed by others.

**Comment by weshinsley** [comment]
To add to this, please read report 9 properly. The 500k UK prediction was if governments did nothing whatsoever - we never believed governments would do *nothing* but we modelled it as a base case, because that's part of what you do when you model.

With the full social distancing the report suggestd it might be possible to reduce deaths perhaps to 20k - a death count we have already exceeded. Nobody here is laughing about that. The report was also very frank about the uncertainty involved in trying to predict what might happen at that stage
