### ISSUE TITLE
Wow- you guys how many issues are you going to close?

### ISSUE THREAD

**Issue by SRGOM** [mrc-ide/covid-sim#181]
Are you not going to address any concerns?

**Comment by SRGOM** [comment]
Mr smarty pants here says Microsoft and Github have helped him refactor and clean up the code. 

https://i.4cdn.org/pol/1588884856551s.jpg 

Microsoft it shows badly on you guys if you do shit like this. Github of course is shitty silicon valley company. But at least you have some standards. (shoudn't have bought the POS)

**Comment by beewenib** [comment]
Can't agree more. At least one of them is a totally legitimate bug: https://github.com/mrc-ide/covid-sim/issues/175

**Comment by DanBuchan** [comment]
@beewenib A statistical model making an incorrect prediction is specifically NOT a bug in the code. 

If you believe that the code does not implement the algorithm as described in the literature then by all means find the inconsistencies in the code and add the relevant bugs/issues here.

If what you're trying to say is that the statistical model, as presented does not output plausible figures/outcomes that is not an issue of code correctness. You've moved in to a discussion of the science and the appropriate modelling. You are free to write a paper rebutting the author's scientific and statistical methods and submit it to the appropriate journals or conferences. It is totally valid to make such a critique but that is way beyond the scope of the code's bug tracking system.

**Comment by dhogaza** [comment]
"You are free to write a paper rebutting the author's scientific and statistical methods and submit it to the appropriate journals or conferences. It is totally valid to make such a critique but that is way beyond the scope of the code's bug tracking system."

Or a blog post, blogscience being such a thing these days.   More seriously, there are ways to make such a critique that doesn't require quite the formality of a paper or conference submission.

But such things are not model implementation issues, as you say.
