### ISSUE TITLE
File actual issues with the code (and maybe use Jira for tasks)

### ISSUE THREAD

**Issue by Feynstein** [mrc-ide/covid-sim#187]
This is the most important one... People from the community need to stop s***posting and start working on this thing in order to make it better.

**Comment by chanhosuh** [comment]
Using labels would be helpful too, I imagine.  It's rather unclear looking through the repo, which issues are minor and which are serious.

**Comment by Feynstein** [comment]
Yeah, that would be a good idea, if a Jira type software cannot be used

**Comment by Feynstein** [comment]
Lets get them started the right way!

**Comment by DanBuchan** [comment]
Just to note when you make new github issues you can add labels (menu on the righthand side). And you can edit/add labels you needs. You can also add labels to existing issues if people didn't do so or you need to change them. So there's no need to precede issue Titles with a label as you've started doing.

**Comment by Feynstein** [comment]
Ok I'm not used to working on GitHub, we use the Atlassian suite at work and I don't have much experience with open source. Thanks I'll do that!

**Comment by bbolker** [comment]
The other thing that would probably be helpful would be to provide links to specific lines of code rather than screenshots, e.g. https://github.com/mrc-ide/covid-sim/blob/master/src/Bitmap.cpp#L48-L50 (rather than the screenshots in  https://github.com/mrc-ide/covid-sim/issues/196)

**Comment by Feynstein** [comment]
Yes thank you everyone... but I think than instead of saying what to do you should do stuff yourself if you're more comfortable with this whole setting. This would give an example of how to do stuff around here. It seems to me that a whole bunch of people like telling others what do to but don't actually touch anything...

**Comment by Feynstein** [comment]
So yeah, instead of noticing how unfamiliar I am with the open source community, just do a couple of real examples and then we'll move on from that...

**Comment by bbolker** [comment]
I really do appreciate your good intentions, and I'm trying to criticize constructively.  I don't actually have a lot of time to work on this project myself at the moment ... what I'm trying to say is that the actual developers of this code are probably *seriously* overwhelmed/in crisis mode running scenarios, responding to requests for information (not to mention fending off idiots), etc. etc., so the easier we can make things for them the better.   You've suggested branching/forking and working on some of these issues in parallel - that seems to me like (by far) the best way to proceed (i.e., open an issue for general discussion, then make a branch/fork where you start to implement the ideas you've discussed).

**Comment by Feynstein** [comment]
Thank you, I appreciate your comment, and I know it's constructive. I'll think about that. I guess I just came out too hard on it as I always do, but I'll do the work they need in the background now.

**Comment by chanhosuh** [comment]
I almost feel there should be a "Don't feed the troll" label, given the multiple petition-like or blog rant-like issues people keep opening.
