### ISSUE TITLE
Shadow variable

### ISSUE THREAD

**Issue by n3150n** [mrc-ide/covid-sim#188]
https://github.com/mrc-ide/covid-sim/blob/de9732e7715cfaa1a8ee6ba0aa85d13773b2b11a/src/Update.cpp#L812

Shadows variable in line 774.
Same happening in line 816

**Comment by Feynstein** [comment]
@n3150n Can you edit your issue name with the current labels? I suggest [CS-xx][Very High] for this one

**Comment by Feynstein** [comment]
Nevermind the numbering I forgot github had that

**Comment by weshinsley** [comment]
Let's talk about this one on  #169, as there are more j-confusions before it. I think it is functionally fine, but rather unclear.

**Comment by n3150n** [comment]
Agree.

**Comment by n3150n** [comment]
already addressed in #169
