### ISSUE TITLE
Release the original Source Code and Config files

### ISSUE THREAD

**Issue by sylaxofficial** [mrc-ide/covid-sim#198]
This will cause an uproar if you do not show the original source code of what influenced the UK's decicion that could cause many to die or live. You have refused and this will not go unnoticed.

**Comment by Feynstein** [comment]
This is not the right place for this issue. I suggest you contact microsoft, github and/or their college in order to submit a formal request. It's useless to make that request here as it is intended for people to work on the modified version. If they ever release the original it will probably not be in that repo anyway. thanks.

**Comment by bjcband** [comment]
ok retard.. i can leave... refer to 178

**Comment by bjcband** [comment]
179

**Comment by UlisseMini** [comment]
@Feynstein I think the idea with asking again here, is that in a formal request you can be ghosted with no recourse, Here is better because a decision must be made. I don't know about you, but I have very little faith in a "formal request" and doubtless many have already submitted "formal request"s.

**Comment by sylaxofficial** [comment]
I don't have to understand the code completely to read the other Issues and see the bullshit they are saying. And do you really think microsoft/github/their college will give a shit? Here is the right place to complain about what they are doing. They do have an original copy (refer to 179), yet they argue so hard to not release it. This is not some random project on github. This program was used by the government and they are refusing to give the original version the government used that could cost lives of people that did not need to die. I see you arguing real hard against this shit in all the other repos... Do you really care that much about releasing the original?

**Comment by sylaxofficial** [comment]
Release the un-modified code that was used for report9 and release the configuration files.

**Comment by Feynstein** [comment]
@UlisseMini It's not like they can "unlock" the code's history. It was uploaded as-is. Any reference to earlier code is against normal repo usage. I don't care if you can or can't make a formal request and I even care less about what is happening around it because I don't live there. I know it was not that way in other issues because I was pissed, but now I'm talking as a neutral representative of the real people that try to work here. Leave that repo alone, please.

**Comment by rittersb** [comment]
@Feynstein I have been reading the majority of these posts, and it seems that you like to interject yourself a lot in conversations that are not directed at you. You like to call people names which for the most part people ignore you after you write pages and pages of pointless ranting. I mean I am no open-source aficionado myself, but just because I don't have a glowing repo doesn't mean I don't work with C and C++ daily. I mean one could say the same thing about your repo too.

**Comment by UlisseMini** [comment]
@Feynstein 
![image](https://user-images.githubusercontent.com/26258618/81483150-e0acbf80-9209-11ea-98d5-c1b48e632708.png)

It was clearly not uploaded as is, have you even read #144?

**Comment by sylaxofficial** [comment]
@Feynstein Same thing here. I find it rediculous that the same people supplying the government with covid simulations, can't even keep track of their versions. There is no point of something being "open source" if it doesnt even show the original.

**Comment by Feynstein** [comment]
@sylaxofficial Read what I wrote kid and why I wrote it. If you've never experienced academia you can't just come here and give shit to people. That's the point I was making in other issues. These people work in an academia lab, their boss is involved with the government, they are not. And the only person that actually comes here that is a collaborator can't do shit, he can't even merge pull; requests. ..... It was uploaded as is meaning the first commit... look at it.... god... obviously it was modified... Git hub is not the place for politics.

@rittersb Well, I was trying to point out the obvious minecraft-y part of his repo... I just uploaded some python code I was doing for a project exactly for that reason lol... let me just upload what I can and then we'll talk if that's what you want. And I was pissed

**Comment by Feynstein** [comment]
@rittersb Considering all I told you, who's pointlessly ranting?

**Comment by sylaxofficial** [comment]
![image](https://user-images.githubusercontent.com/58594562/81483177-0353ce00-9234-11ea-8af0-121fd5e8707e.png)
This is also one of the problems. There is no point of it being open source if we go along someones trust. What are you trying to argue here? Retards these days

**Comment by sylaxofficial** [comment]
Why do you think people have major distrust in the governments numbers? Check any uk covid-19 report on youtube by a news channel and the dislikes outway the likes by a shit ton. He said that "even if we release it" subconciously implying they do have it to publish, yet are not.

**Comment by Feynstein** [comment]
@sylaxofficial Lol go back to your basement.... read what is written... if you can't understand this particular code, what in the world makes you think you could understand the original 19 000 lines shitty one pager.

**Comment by Feynstein** [comment]
@sylaxofficial I don't give a shit about any of what's happening, here is simply not the place to do that... and I hate politics anyway.

**Comment by sylaxofficial** [comment]
You are showing yourself as toxic and uncomposed. We are talking about releasing the code and not me understanding it. There are many people that can, that want to, but I am simply here because they closed ticket #144 for no reason except their poor excuses. If you dont like politics and anything that is happening, fuck off then.

**Comment by UlisseMini** [comment]
@Feynstein Please stop ranting, you are adding nothing to this conversation.

Firstly, we don't need to understand it; the world needs to understand it. There are many epidemiologists who want to see the original code & verify the results. What kind of pseudoscience are you pushing? I thought academics were for peer review?

**Comment by sylaxofficial** [comment]
If you do not care, why are you commenting so much 🤔🤔🤔

**Comment by Feynstein** [comment]
@sylaxofficial its not any conspiracy I just personally think that the people responsible are reasonably scared to do it while its still on fire...Fuck off yourself kid... don't pollute the repo I'm trying to help desperately. and as for your question about me commenting see #194 youll see why I care. And then again, fuck you :-) and go back to you basement :-)

**Comment by sylaxofficial** [comment]
Lmao the salt

**Comment by sylaxofficial** [comment]
You're mad

**Comment by sylaxofficial** [comment]
I am asking for a version release which they have. 🤔🤔🤔

**Comment by Feynstein** [comment]
@sylaxofficial see #194 hahaha omg you're perfect... I feel like i'm in COD all over again

**Comment by sylaxofficial** [comment]
You are now mad at me for asking for a release 🤔 Give me a good reason why they cannot release the original 🤔

**Comment by Feynstein** [comment]
@UlisseMini see #194 youll understand... I might even publish my master's thesis in here... hum why not... its under review right now but it could do with some help!
@sylaxofficial im not mad I'm responding to insult with insult, that's what I do with my nephew when he's trowing a tantrum. I don't care about the release, stop polluting the repo.

**Comment by sylaxofficial** [comment]
You did not answer the question, you completely ignored it.

**Comment by Feynstein** [comment]
@sylaxofficial There's no good reason appart that they don't want to... I don't know more than you about that and it actually transpires in my issue #194 ... yeah you got me good whouuu i'm not answering because I'm illuminaty reptilian 5G burning coronavirus muahahaha

**Comment by Feynstein** [comment]
@sylaxofficial come on grow up... last comment in this ive got work to do in order to really help them.... and by the GO READ #194

**Comment by sylaxofficial** [comment]
I like how you lose an argument so you start throwing insults. Why are you even arguing here then?

**Comment by Feynstein** [comment]
@sylaxofficial I'm not insulting you, was I now? By the way... #194 is how you ask a question to another scientifc person... and they answer you... do you know what I did there?

**Comment by sylaxofficial** [comment]
All the things I have to say are posted by the author of #144 and #179 
![image](https://user-images.githubusercontent.com/58594562/81483618-7874d280-9237-11ea-844b-14f5157d3390.png)
![image](https://user-images.githubusercontent.com/58594562/81483623-8296d100-9237-11ea-832e-848615d49256.png)
🤔

**Comment by Feynstein** [comment]
@sylaxofficial yes... is #179 still open or not? Is it a duplicate then? THAT WAS AN INSULT? REALLY?

**Comment by Feynstein** [comment]
@sylaxofficial I'm actually starting to enjoy this conversation now... I might keep it open... please carry on

**Comment by sylaxofficial** [comment]
> 
> 
> You are showing yourself as toxic and uncomposed. We are talking about releasing the code and not me understanding it. There are many people that can, that want to, but I am simply here because they closed ticket #144 for no reason except their poor excuses. If you dont like politics and anything that is happening, fuck off then.

**Comment by Feynstein** [comment]
Thank you for adressing the dupe issue, you can carry on in #179
