### ISSUE TITLE
Implement the trolley class for I/O and data handling

### ISSUE THREAD

**Issue by Feynstein** [mrc-ide/covid-sim#201]
I just thought of a particular data container that could be used to move the data around the algorithm. I unexpectedly let my thoughts flow on it in #193 --- I'll collect all of them in a bullet point list...

1. Create a class that contains a unordered_map<std::string, std::any>
2. Implement getters and setters
3. In the Ctor, load a config file (xml or txt) in order to prepare it for data handling, it will contain all the strings defining the different keys.
4. Make sure to document every type of data that is used in it bc it is lost in the std::any and you have to use std::any_cast<T> in order to recover it
5. Use it as a form of delay-load to try and save RAM... like only load some parts at some times, etc...
6. Use conditions to check the data and throw or skip if the needed data is present or not
7. Just before the execution of a piece of code you unload what you need (and erase it if needed) into a shared array, since performance is necessary that way you don't have the overhead of a std::vector during execution... it could be done with a simple memcpy to save time
8. When initializing the class, put it in a smart pointer so that if you don't need it anymore it automatically dies.

It will remove the thousands upon thousands of definitions because in the back of it it will only be strings carrying all the information about what's in the map and will be contained in an external xml or txt file that is loaded on instanciation. This file will contain all the strings of the keys and when setting and getting there will be a verification done in order to check if its in one of those strings. Also, very important that the documentation will need to be updated so that we keep track of the types of the values in the map as it is lost when put in std::any.

At first I plan to use the name of the variables as the keys so that I can trace the code properly with it and use it at every occurences of the use of the original parameters. But once this is done, adding parameters or changing their name is only adding a line in a text file...

Because of the std::any you can add scalable complexity at the shake of a wand.. like different levels of complexity that load and unload at different times... I already saw something like that somewhere but never let my thoughts flow on it like I just did... doing this in my fork...

**Comment by Feynstein** [comment]
By the way I now have the help of a friend undergrad in computer engineering, I don't know for how long he'll be able to help but that's one more to do some grunt work with me! He will try to run the algorithm as-is so that we can begin tracing it properly. @ggodbout796

**Comment by CallumAttryde** [comment]
A couple of things to consider:

- this introduces a minimum supported version of C++17. I don't believe the maintainer has made any specifications on what versions are to be supported, but considering the current code lacks many features of C++03 it would be good for some clarification 
- an in memory key-value cache is a fairly common tool and as such there are several battle proven OSS solutions, for example [redis](https://redis.io/)

**Comment by Feynstein** [comment]
Closing considering the live code fact, will work in fork.
@CallumAttryde whew I'm glad I'm not the only one who though of that! What a mess would our world be, eh? Do you have other out of the box constructive comments like that?
