### ISSUE TITLE
Copy of the contract with Microsoft and Github

### ISSUE THREAD

**Issue by pdehaye** [mrc-ide/covid-sim#212]
In #209, @weshinsley mentions

> Some might consider Microsoft and GitHub to be actual professionals; as I see it, their offer for help included the capacity, expertise, and relevant modelling experience to review the code and make it more reviewable in a tight timeframe, without requiring us to top-manage or train individual coders - none of which we had/have any capacity for.

Could the copy of the contract(s) with Microsoft and GitHub be included in this GitHub repository (or alternatively sent by email to freedomofinformation@personaldata.io), as per the UK Freedom of Information Act? Alternatively, could you advise on which authority to refer to on this matter on the [website WhatDoTheyKnow](https://www.whatdotheyknow.com/body/list/all)?

**Comment by weshinsley** [comment]
This is an issue tracker, used for reporting and discussing the code within this repo. Info about how to make an FOI concerning Imperial contracts can be found very easily by googling such terms. https://www.imperial.ac.uk/admin-services/secretariat/information-governance/freedom-of-information/

**Comment by pdehaye** [comment]
I didn't know where to ask. Thank you for clarifying. 

You might want to clarify somewhere in the repository that you only welcome on GitHub those issues that have to do with _code_, and not those relating to how that code has been produced.

**Comment by pdehaye** [comment]
For those interested, the request is [here](https://www.whatdotheyknow.com/request/contract_with_microsoft_and_gith).
