### ISSUE TITLE
Log of a negative?

### ISSUE THREAD

**Issue by kngott** [mrc-ide/covid-sim#22]
In Line 2203 of Rand.cpp,
   `} while ((z <= (-1.0 / c)) && (log(u) >= (0.5 * z * z + d - d * v + d * log(v))));:`
v is not always positive.

So the test is equivalent to:
`while ( (z <= (-1.0 / c)) && (v == 0. or (v>0. and (log(u) >= (0.5 * z * z + d - d * v + d * log(v))))) );`
, because log(0) = -inf, log(negative number) = NaN and non-NaN >= Nan is false.

Is that intended?

Even if it is intended, it might be better to rewrite to account for this to avoid raising FE_DIVBYZERO and FE_INVALID.

**Comment by weshinsley** [comment]
Fixed at some point to remove possibility of the rare case - && replaced with ||
