### ISSUE TITLE
Practicality of using a third party geographical library

### ISSUE THREAD

**Issue by zebmason** [mrc-ide/covid-sim#220]
Obviously this may be a complete distraction. I'm raising this because I don't have a GIS background and hope that someone reading this does.

Currently the code uses 2D points of types int, float and double which it transforms between. For the float type it calculates distances between points in an appropriate co-ordinate system. Axis aligned bounding boxes are used for double and int, the latter in the bitmap calculations.

The non-functional requirements would appear to be low overhead in both memory and processing.

Is there a maintained third party library that could replace the current geographic functionality? e.g. [Boost](https://www.boost.org/doc/libs/1_73_0/libs/geometry/doc/html/index.html), [GeographicLib](https://geographiclib.sourceforge.io/) may be possibilities if you'll forgive the solutioneering.

I've already done a rough refactoring of the current code, #213, on the basis that this will ultimately be replaced by third party code. If not I'll refine the code.

**Comment by matt-gretton-dann** [comment]
The requirements I have (and these apply in general):
 * Works on Windows & UNIX like (Linux-based & macOS at least) platforms.
 * License compatible with GPLv3 when *statically* linked
 * No install steps required on any platform over and above copying a single `CovidSim` executable.
 * Simple to integrate to the current build systems (in particular Visual Studio) - by which I mean no extra steps after cloning the repo if at all possible.
 * Can be implemented without major changes to the current usage models.

These are to ensure that development of model features is not slowed down by re-engineering going on at the same time.  I acknowledge that the above may be non-optimal, but the model is in active development and use, and so I'm being conservative about significant changes.

I'm happy to take suggestions based on the above as I am not familiar with the various libraries.

**Comment by Feynstein** [comment]
@zebmason I think thats PCL could be of good use:
https://pointcloudlibrary.github.io/

**Comment by zebmason** [comment]
It would seem that a proper geometry library is all that is needed.
