### ISSUE TITLE
Why maintain 2 build systems?

### ISSUE THREAD

**Issue by zebmason** [mrc-ide/covid-sim#224]
I was used to using the CMake GUI to generate Visual Studio projects and then Microsoft allowed the direct opening of CMake folders within Visual Studio. So why not delete the sln and vcxproj files?

**Comment by zebmason** [comment]
Just updated my branch for #213 where I added in unit tests to CMake but couldn't be bothered with the overhead of creating the vcxproj files.

**Comment by matt-gretton-dann** [comment]
One of the primary development environments is Windows, and when we tried to move to Visual Studio's builtin CMake support we found that it lacked support for various external tools that were also in use in the development process.  Therefore, we have kept two build systems.

**Comment by zebmason** [comment]
@matt-gretton-dann Thanks, I'd suggest moving the vcxproj file into a subdirectory so that any extra such files can be placed there otherwise I'd imagine the root directory will get rather busy. On a related note the filter file isn't committed, should it be?

**Comment by zebmason** [comment]
@matt-gretton-dann Another thought is that Visual Studio uses Ninja as the generator whereas the CMake GUI uses a different generator. Maybe using the latter would solve your tool issue?

**Comment by zebmason** [comment]
I suppose that an implication of having 2 build systems is that third party libraries are limited to either header only or those provided by an appropriate package manager

**Comment by matt-gretton-dann** [comment]
> @matt-gretton-dann Another thought is that Visual Studio uses Ninja as the generator whereas the CMake GUI uses a different generator. Maybe using the latter would solve your tool issue?

Experience was that either generator didn't produce usable solution files to integrate third-party tools.

**Comment by billhoffman** [comment]
> One of the primary development environments is Windows, and when we tried to move to Visual Studio's builtin CMake support we found that it lacked support for various external tools that were also in use in the development process. Therefore, we have kept two build systems.

What are the external tools missing? I might be able to help Kitware has worked closely with the Visual Studio team to improve the CMake integration.

**Comment by zebmason** [comment]
@billhoffman I have written a libclang (ClangSharp) based [tool](https://www.deepends.co.uk/) that uses a rather rough and ready [CMake parser](https://github.com/zebmason/CMakeParser) written in C#. Since I've started using the tool on this project I've fixed a few bugs in both the C++ and CMake parsing.

Have you any suggestions for a third party CMake parser?

**Comment by billhoffman** [comment]
I guess I would suggest not using a CMake parser.  Instead use the CMake file API that VS and other IDE's use.  https://cmake.org/cmake/help/git-stage/manual/cmake-file-api.7.html. Aside from that how is your tool integrated into VS? Seems like that is the real problem. In your custom vs project you are able to use your tool but in the built in cmake support you can't?  What about the cmake generated VS files? Can it be made to work from there?

**Comment by zebmason** [comment]
Thanks, I'll give that a try.

DeepEnds was originally a Visual Studio Extension but that was hard to maintain so I cut it down to a command line application as the GUI was just gathering parameters. The results are viewed in the DGML editor and the output window of Visual Studio (stream a text file formatted for navigation using Tools >> External Tools >> cmd.exe /c type filename). So nicely separated for maintainability. It also uses a rough and ready *.sln parser.

**Comment by zebmason** [comment]
Superseded by #410
