### ISSUE TITLE
Should CMake be used to build Doxygen docs?

### ISSUE THREAD

**Issue by zebmason** [mrc-ide/covid-sim#225]
Trivial to set up as a CMake option but the Doxyfile would need turning into a template so #224 is relevant. This would then allow a CI system to track the number of Doxygen warnings.

**Comment by zebmason** [comment]
Just run Doxygen and it doesn't know the dot path which CMake can detect and set

**Comment by matt-gretton-dann** [comment]
Feel free to create a PR to do this as the Visual Studio project doesn't build the docs so this can be a CMake only target.  Note there is a .github/workflow that generates the docs which will need updating.
