### ISSUE TITLE
Create an experimental branch/repo/fork where big changes can be tested

### ISSUE THREAD

**Issue by Feynstein** [mrc-ide/covid-sim#231]
If you want the community to really help, you need to create an experimental branch/fork/repo where it can make pull-requests and issues to really start advancing this model. As stated in #229 it could be run in parallel to the real model in order to check if the results still fit. 

This will make greater steps possible because now it seems like only small incremental conservative changes can be made because this repo is used for real computations (which is something I didn't think was happening). It really cannot continue like that.

**Comment by Feynstein** [comment]
We are a bunch of professionals who really want to make this thing work the right way and right now we are confined into our own forks without having much feedback from the maintainers of this repo. I think that adding such branch and running it somewhere in parallel (I think I can deal something with compute canada...) will be a better thing. I think that if this not adressed I will start a new repo called covid-sim-experimental where I will copy all the original code and let people work on it.

**Comment by Feynstein** [comment]
Im sorry for coming out hard on this... but I, and probably a bunch of other people, really want to help you get a bit of load off your shoulders....

**Comment by weshinsley** [comment]
Thanks for your enthusiastic help with this - sorry we can't quite keep up at times.

YES - the repo is most definitely used in real live computations fairly continuously, so we have to be careful about big changes, and generally the things that are getting merged in (including those from people's forks), are changes that we can get on top of fairly easily. I'll ask one of the github team to  comment a bit more - they may be able to answer this better than me.

**Comment by nash3d** [comment]
You can create your own fork. You don't need to raise an issue for this. If you come up with something worth putting into the original project, you can issue a pull request.

**Comment by Feynstein** [comment]
@nash3d omg did you actually read what I wrote? look at #229 to see why it is a current issue... incrementally conservative changes only... thats not getting us anywhere. Its good for the in-use model but nothing else.

**Comment by matt-gretton-dann** [comment]
@Feynstein: This model is in continuous use and development and so I am being conservative and cautious in what I think should be accepted as changes to the repository.  So that those who are developing the core model are not surprised by changes to the code as they move things forward.

You are of course free to create a fork and push your own changes to that and raise PRs with changes you propose - but movement here at the moment is deliberately slow and steady.

**Comment by Feynstein** [comment]
@weshinsley Thank you very much! And I am asking that because such a branch needs to be run in parallel to the real algorithm to compare the outputs and make sure nothing breaks... As I said, I have contacts lol... you just need to tell me the word and I'll make sure you get covered XD

**Comment by Feynstein** [comment]
@matt-gretton-dann this would be the exact purpose of an experimental/unstable branch... but working alone on it doesnt make it and I dont have the Issue mechanics in my fork in order to have more people working on it. Thats Why I first proposed to actually copy paste the code in my own repo and add relevant people as maintainers, and have access to the whole issue/pull-request mechanics... but I removed this comment as I waited for your answers...

**Comment by Feynstein** [comment]
I think that such a branch should be created by the code owner for obvious legal reasons.

**Comment by edwardaskew** [comment]
@Feynstein you can enable issues in the repository settings and I don't see any legal reasons not to have a third party fork - that's what the GPL is *for*. If you'd prefer, I'd be willing to host the unstable fork but my time at the moment is fairly limited (the curse of being able to work remotely...)

**Comment by Feynstein** [comment]
@edwardaskew Thanks for the tip, I do not know github that much, im still getting used to it.

**Comment by edwardaskew** [comment]
If no one else has set up an experimental fork by the weekend (when I actually get some time to work on it) I'll clean up my fork and start inviting people as collaborators.

**Comment by Feynstein** [comment]
@edwardaskew I already created one which is a re-upload of the code (to get the fork stuff out of the way) how did I invite people to it?

**Comment by edwardaskew** [comment]
@Feynstein you'll find the option under settings->Manage Access

**Comment by Feynstein** [comment]
@edwardaskew hi, I just invited you, I have to take my covid test this morning but when I come back I will invite more people to collaborate. Unless you can do it while I'm gone, which I don't know

**Comment by edwardaskew** [comment]
Thanks for the invite.

> Unless you can do it while I'm gone, which I don't know

I can't, only the repository owner can do that, you can see what things only you can do [here](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository#owner-access-on-a-repository-owned-by-a-user-account)

Hope the test is negative!

**Comment by bbolker** [comment]
@Feynstein , I'm going to argue that a fork will be better than a brand-new repository

- the fork will maintain the previous history of the repository
- it will be easier to synchronize ongoing changes in the main repository with the experimental branch
- it will be easier to synchronize improvements in the experimental branch with the stable branch

**Comment by Feynstein** [comment]
@bbolker yeah I get you... my fork is a bit messy right now though... wait a bit...
@edwardaskew I'll reinvite you

**Comment by weshinsley** [comment]
I think this one has run its course so cleaning up. General outcome: making your own fork of the repo is fine; we don't really want to be maintaining an extra experimental one ourselves.
