### ISSUE TITLE
Which C++ unit test framework?

### ISSUE THREAD

**Issue by zebmason** [mrc-ide/covid-sim#233]
In PR #213 I've used GoogleTest as I am very familiar with it. I'm using it as a submodule so have disabled building the unit tests due to the CI VMs not doing a git submodule update although I suppose that could be my fault.
In #166 at least one other framework is mentioned.
Does MRC have any preference for a particular framework and can we get support into the master branch?

**Comment by Feynstein** [comment]
I know that they might prefer something more lightweight, that's why I suggested Catch, it's only one header.

**Comment by matt-gretton-dann** [comment]
I am happy with Google Test as you can integrate it into CMake's CTest framework quite easily.

**Comment by zebmason** [comment]
#331 updates the CMake version for the containers (finally, what a mess around that was)
then #324 will use the newer version to pull GoogleTest down once a couple of lines are uncommented
