### ISSUE TITLE
Alignment in Model.h

### ISSUE THREAD

**Issue by StevenWhitehouse** [mrc-ide/covid-sim#249]
I'm wondering what the reason was for the #pragma pack(push, 2) in Model.h. That seems an odd requirement for code that is presumably intended to be fast. Looking down the structures which are in that region, one in particular caught my eye, which is struct HOUSEHOLD. The reason is that if the compiler does align on a 2 byte basis the two floats in that struct are misaligned (i.e. 4 byte variables which will be on a 2 byte boundary).

Also, the field dum in struct POPVAR is never used, so can be removed. If that was added for alignment, then it is the wrong size, since CACHE_LINE_SIZE is in bytes, and with the two byte alignment being enforced, it is unlikely to produce the desired effect, although I didn't count the offset from the start of that struct to verify. It doesn't look like alignment should be needed at that point anyway.

I've copied & pasted a patch below with the proposed changes. While I was looking there are probably a couple of further things that can also be cleaned up (not included in the patch) which are:

- In struct POPVAR the nct_queue field is initialised, but otherwise appears unused, so possibly could be removed too. 
- Also the three bitfields towards the end of struct PERSON, namely digitalContactTraced, index_case_dct, and digitalContactTracingUser could be moved up next to the earlier set of bitfields (esocdist_comply, keyworker, to_die, detected) to save an unsigned int from that structure.

```
diff --git a/src/Model.h b/src/Model.h
index 801b185..218a209 100644
--- a/src/Model.h
+++ b/src/Model.h
@@ -11,8 +11,6 @@
 //// need to test that inequalities in IncubRecoverySweep can be replaced if you initialize to USHRT_MAX, rather than zero.
 //// need to output quantities by admin unit
 
-#pragma pack(push, 2)
-
 typedef struct PERSON {
        int pcell;                      // place cell, Cells[person->pcell] holds this person
        int mcell;                      // microcell, Mcells[person->mcell] holds this person
@@ -55,8 +53,8 @@ typedef struct PERSON {
 typedef struct HOUSEHOLD {
        int FirstPerson;
        unsigned short int nh; // number people in household
-       float loc_x, loc_y;
        unsigned short int nhr;
+       float loc_x, loc_y;
 } household;
 
 /*
@@ -111,7 +109,6 @@ typedef struct POPVAR {
        int* CellMemberArray, *CellSuscMemberArray;
        int** InvAgeDist;
        int* mvacc_queue;
-       int dum[CACHE_LINE_SIZE];
        int nct_queue[MAX_ADUNITS]; // queue for contact tracing: ggilani 12/06/17
        contactevent* dct_queue[MAX_ADUNITS]; //queues for digital contact tracing: ggilani 14/04/20
        int ndct_queue[MAX_ADUNITS]; //queues for digital contact tracing: ggilani 10/03/20
@@ -329,7 +326,6 @@ typedef struct ADMINUNIT {
        double* origin_dest; //storage for origin-destination matrix between admin units: ggilani 28/01/15
 } adminunit;
 
-#pragma pack(pop)
 
 extern person* Hosts;
 extern household* Households;
```

**Comment by zebmason** [comment]
Steven, that's interesting. I was wondering why #252 was failing on its build but hadn't had chance to check - I deleted all unused fields that a tool had detected but was worried about the snapshot functionality.

**Comment by StevenWhitehouse** [comment]
Ah, if those structures are being used for I/O, then yes, that might be a problem. I'll check on that when I get a chance, but a good thought since that might be an issue.

**Comment by weshinsley** [comment]
Memory usage might have been part of the use of that pragma - for a USA run in around 2005, we'd have 300 million of these structs, and in limited ram, packing to 2-byte granularity might have been necessary. Perhaps less so now...!

**Comment by CloneDeath** [comment]
Do/should we have to maintain compatibility with previously saved snapshots?
I would hope not, and would prefer the snapshots only be compatible with the version of the code they were generated with, otherwise, it's going to be a LOT more difficult to develop this simulation.

I think we should either drop the packing, or as a compromise in case anyone disagrees, only apply it to the structs specifically that would benefit from it (or that are saved in the snapshot), as opposed to ALL of them.

**Comment by geoffw0** [comment]
To answer your original question with a tiny bit of historical context, I believe `#pragma pack(push, 2)` helped to reduce the size of `PERSON` at one time.  This is important because millions of `PERSON`s are allocated accounting for a large proportion of memory used by the simulation.  However the structure has changed several times recently, so the `pragma` may not make a difference any more.

**Comment by NeilFerguson** [comment]
It might be worth checking what the memory-performance tradeoff actually is here. I agree 2 byte alignment is ugly on modern architectures. But if the cache misses are the bigger issue, then it may not cost much. Past testing suggests that NUMA memory bandwidth is the biggest performance constraint on large population runs.

**Comment by StevenWhitehouse** [comment]
So to measure the performance impact of misalignment, I wrote a small program to check...

```
#include <stdio.h>
#include <unistd.h>
#include <time.h>

#define NR_TESTS 100000000

#pragma pack(push, 2)

struct a {
        unsigned short x;
        float y[NR_TESTS];
};

#pragma pack(pop)

struct b {
        float y[NR_TESTS];
};

static struct a aa;
static struct b bb;

static void test_a()
{
        int i;

        for (i = 0; i < NR_TESTS; i++)
                aa.y[i]++;
}

static void test_b()
{
        int i;

        for (i = 0; i < NR_TESTS; i++)
                bb.y[i]++;
}
static struct timespec timespec_diff(const struct timespec *start, const struct timespec *end)
{
        struct timespec temp;

        if ((end->tv_nsec - start->tv_nsec) < 0) {
                temp.tv_sec = end->tv_sec - start->tv_sec - 1;
                temp.tv_nsec = 1000000000 + end->tv_nsec - start->tv_nsec;
        } else {
                temp.tv_sec = end->tv_sec - start->tv_sec;
                temp.tv_nsec = end->tv_nsec - start->tv_nsec;
        }
        return temp;
}

static void time_test(void (*test_fn)(), const char *msg)
{
        struct timespec start, end, diff;

        if (clock_gettime(CLOCK_MONOTONIC, &start) != 0)
                perror("clock_gettime: start");
        test_fn();
        if (clock_gettime(CLOCK_MONOTONIC, &end) != 0)
                perror("clock_gettime: end");

        diff = timespec_diff(&start, &end);

        printf(msg, (double)diff.tv_sec + (double)diff.tv_nsec/1000000000.0);
}

int main(int argc, char *argv[])
{
        time_test(test_a, "Unaligned: %lf\n");
        time_test(test_b, "Aligned:   %lf\n");

        return 0;
}
```
On my (intel) laptop, that seems to result in somewhere between 6 and 7% slowdown. However Intel is generally fairly good at this compared with other architectures. Trying a non-Intel server class machine, the slow down was closer to 22%.

It is often true that the main cost of locking is the cache effects on the variables used to implement the lock, rather than the actual lock itself - at least if there is much contention there. NUMA effects can also play a big part. I've not got to grips with the data access patterns here enough to be able to figure all that out though. Also, while I've written a lot of multi-threaded code before, OpenMP is something new to me, so I'm not quite sure what it is doing yet. Well I know roughly what it is doing of course, but not in the kind of detail to understand if/where there may be bottlenecks.

If it is possible to reorder the fields in Household then it should be possible to fix that misalignment easily. I've still not checked to see if it is used in I/O. It is on my todo list, if nobody else gets there sooner. There might be misalignments in some of the other structures too, but those are large enough that it is not easy to see at a glance.

**Comment by NeilFerguson** [comment]
Thanks - that’s great. No problem to reorder fields in almost any struct.

Best,

Neil
________________________________
