### ISSUE TITLE
Add function to check if person is dead or alive

### ISSUE THREAD

**Issue by CloneDeath** [mrc-ide/covid-sim#291]
I see a lot of code that looks like `abs(Hosts[j].inf) != InfStat_Dead`.

I'd like to introduce `isDead()` and `isAlive()` functions to person in order wrap this check.

Edit: I wanted to assign this ticket to myself, as I was planning on doing this tonight, but it looks like I don't have permissions.

(honestly, this ticket is so I don't forget).

**Comment by seanmorris** [comment]
🤡🌎

**Comment by CloneDeath** [comment]
Please, be professional. Thank you :smile:
