### ISSUE TITLE
Use a widely-available coding style and enforce it

### ISSUE THREAD

**Issue by zdroid** [mrc-ide/covid-sim#305]
This is fairly easy to do with VS Code / Visual Studio. This project's code is currently highly unreadable and that's very detrimental to the future development. `Visual Studio` style is very similar to this project's one, among the widely-available ones.

There is also a lot of tab-space mixing which looks horrible on every setup.

**Comment by CloneDeath** [comment]
Agreed. Maybe we should start a contributing guide?

**Comment by ozmorph** [comment]
I agree as well.

I would personally prefer 4 spaces to tabs simply because they make GitHub Pull Requests easier to read. GitHub's code view defaults a tab to 8 spaces, which in a code base that relies on very nested logic (like this one) makes the code shift to the right so much that it sometimes wraps around.

**Comment by CloneDeath** [comment]
I prefer tabs, but don't care enough to argue it.

Also, take that survey with a grain of salt, as it really is more of a reflection of what IDEs are popular and their default settings.

I say we just start with a popular style guide that sort of matches what we want the code to look like (not necessarily what it is now), and make adjustments from there.

**Comment by ozmorph** [comment]
Very true about the survey and its findings. I won't argue the tabs vs. spaces debate, just stating my personal preference. I'll use whatever the community decides.

**Comment by zebmason** [comment]
During a previous conversation with @matt-gretton-dann he said he'd put together a clangformat file. Other conversations with Matt have resulted in Allman braces everywhere (probably)
Classes & Namespaces: CamelCase
Member variables: snake_case_with_trailing_underscore_
Member methods: snake_case()
Variables: snake_case

**Comment by zdroid** [comment]
@ozmorph There's not really much to argue about there. Diff logs look horrible with tabs, and especially with tabs and spaces mixed. It is configurable, but most of the users will never bother to do that. In case they see a horrible looking code, they won't keep looking.

Using spaces instead of tabs allows a more general config, like `.editorconfig`, to be used for all textual files (R, Python, C++, txt). All coding styles supported by VS Code (Google, LLVM, Visual Studio, Chromium, Mozilla, WebKit) use spaces instead of tabs.

**Comment by CloneDeath** [comment]
> During a previous conversation with @matt-gretton-dann he said he'd put together a clangformat file. Other conversations with Matt have resulted in Allman braces everywhere (probably)
> Classes & Namespaces: CamelCase
> Member variables: snake_case_with_trailing_underscore_
> Member methods: snake_case()
> Variables: snake_case

Personally, I'd prefer snake_case for both public and private member variables, but I'd be willing to concede using trailing underscore for private, if that's popular. However, I MUCH prefer just snake_case for public member variables.

**Comment by yb66** [comment]
@ozmorph You can select a tab size that suits you via CSS. That way everyone can have 2 (my preference), 4 or 8 (or whatever).

https://css-tricks.com/almanac/properties/t/tab-size/

Regards,
iain

**Comment by zdroid** [comment]
@yb66 That requires users to add a browser extension that adds custom CSS to all sites (or to this one at least). And that is exactly something that almost no one will bother to do. Just look at diff logs like https://github.com/mrc-ide/covid-sim/pull/283/files to see how horrible it is.

**Comment by yb66** [comment]
@zdroid 

> And that is exactly something that almost no one will bother to do.

If someone can read a git diff and they're bothered then they know enough to use a custom stylesheet. I also don't know why anyone would waste more than a minute looking at a diff via a web browser but I'm not going to impose my preferences on others. Still, those diffs aren't even hard to read, where's the problem?

It's your problem. Luckily, you already know the answer:

> That requires users to add a browser extension that adds custom CSS

Regards,
iain

**Comment by NeilFerguson** [comment]
Yes, agree tab styles have suffered over the years. I much prefer “Whitesmiths” style brace indents, followed by GNU, followed by the IMO ontologically confused Allman style. I seem to be alone in the group in that view though. 

I don’t have strong feelings re tabs vs spaces. But all the embedded multiple tabs Danny introduced can be removed 😉.

**Comment by zdroid** [comment]
@NeilFerguson I don't really care which style it will be, since I was not the project's author. It can be any.

Only two things are wanted here: style consistency and style availability. First means that the style will be enforced consistently, and the second one is that such style is widely available.

@yb66 

> It's your problem. Luckily, you already know the answer

Most of the developers on GitHub seem to have the same problem. Do you think all of them should just install a browser extension to solve any problem they get? :laughing:

**Comment by NeilFerguson** [comment]
We will discuss internally and try to reach agreement. Not always easy on style issues!

**Comment by zebmason** [comment]
My only concern is getting a .clangformat file available. I'd rather have the computer re-format my code.

**Comment by sublimator** [comment]
> because they make GitHub Pull Requests easier to read.

Not many people know, but you can append `?ts=n` to the end of Github urls to set the tab size: 
e.g. https://github.com/mrc-ide/covid-sim/pull/319/files?ts=2

**Comment by sublimator** [comment]
Having said that ... spaces ftw :) !

Just use something like [prettier](https://prettier.io/) for C++ and get on with it.

**Comment by jieyouxu** [comment]
Possibly useful: `clang-format` has preset formats available (see [Clang-Format Style Options](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#configurable-format-style-options)). It might be easy just to pick a style and just go with it. If customization is needed, just override individual settings.

**Comment by yb66** [comment]
@zdroid 

> Most of the developers on GitHub seem to have the same problem. Do you think all of them should just install a browser extension to solve any problem they get? 😆

No, I think we should all use the same programming language, the same editor, the same OS, the same browser and the same number of spaces because having the _choice_ and the onerous task of using a browser extension is too much for a _developer_ to cope with 😉 

Regards,
iain

**Comment by dlaydon** [comment]
> But all the embedded multiple tabs Danny introduced can be removed 😉.

Ahem, I'm aware the multiple tabs are not everybody's cup of tea. But I argue that they make the code easier to read, as small differences between multiple similar lines can be read near instantly. I appreciate that this style is yet to find favour more widely, but beware the false comforts of consensus.

PS As will be obvious to anybody reading my code, I hate spaces with a passion whose month is ever May.
