### ISSUE TITLE
Refactor the ICDF arrays in Param.h / CovidSim.cpp

### ISSUE THREAD

**Issue by mstevens-uk** [mrc-ide/covid-sim#315]
Linked with #74. (Make Parameter handing more robust)

Concerning
[https://github.com/mrc-ide/covid-sim/blob/master/src/Param.h](https://github.com/mrc-ide/covid-sim/blob/master/src/Param.h)

ICDF arrays are individually defined, and as a result the logic to handle them is duplicated. This could be extracted into classes, then the code in CovidSim::ReadParams() could be reduced accordingly.

**Comment by NeilFerguson** [comment]
I agree - all this was added very rapidly and would be much better properly abstracted
