### ISSUE TITLE
Number of days per year should *at least* be 365

### ISSUE THREAD

**Issue by jieyouxu** [mrc-ide/covid-sim#330]
In `src/Constants.h`, the constant `DAYS_PER_YEAR` is given the value `364`.

https://github.com/mrc-ide/covid-sim/blob/a39e6cd321da3543dc4e1f029e3e65b3ef7791fe/src/Constants.h#L75

In the Julian calendar, years are at *least* `365` days along, and have `366` days every leap year (every 4th year). Even if the mean of this were to be used, then it should be `365.25` days per year? This is the defined conversion for the Julian year to SI days.

Should this be changed to something like

```c++
const double DAYS_PER_YEAR = 365.25; 
```

See https://www.iau.org/publications/proceedings_rules/units/.

I am not sure if this affects the outcome of the model by any means though, I assume there is a reason for the specific `364` value?

**Comment by dhogaza** [comment]
Arrays in C start at 0.  Also, you can only use integers to index C arrays.

**Comment by jieyouxu** [comment]
Thank you, that makes a lot more sense under that context. I understand that this is so the user of this constant does not need to do `DAYS_PER_YEAR - 1` every time when this constant is used as an index into an array (although I personally would favor the explicit `- 1` at the index location, this constant's current name doesn't really convey it's intended semantics).
