### ISSUE TITLE
/PP param

### ISSUE THREAD

**Issue by sje30** [mrc-ide/covid-sim#333]
1. /PP is not defined in the Usage of the CovidSim

2. If I pass  a non-existent file, I simply get an error message about "Update timestamp" not being found.
```
Unable to find parameter `Update timestep' in input file. Aborting program...
CovidSim /c:8 /PP:preUK_R0=2.0.txt /P:p_NoInt.txt /CLP1:100000 /CLP2:0       ...
```

**Comment by weshinsley** [comment]
/PP is listed in the optional arguments here (https://github.com/mrc-ide/covid-sim/blob/master/docs/inputs-and-outputs.md) - although it is one we would usually use. 

The idea is that /PP is for "pre-params", and in that file you would put things common to all the scenarios you want to run, allowing your intervention-specific parameter file (/P) to be simpler and more focussed. You can, if you want, put all of the params in a single file and send it as /P, without a /PP (hence /PP is optional).

But one way or another, you'll need to specify all of the parameters given in our examples (see data/params - look at a "pre_" file, and a "p_" file. We have split ours across the /PP and /P files in a way that seemed intuitive to us. 

Documentation on the specific parameters is something of a work in progress, although many will be obvious by their names. But our examples are the starting point for now, to check you've got them all.

**Comment by sje30** [comment]
hi Wes, sorry I should have been more explicit.

It seems that if I give /PP a file name that doesn't exist, I get no error message that the file doesn't exist -- but simply that it couldn't find the value of the 'Update timestamp' in it.
