### ISSUE TITLE
SpatialBoundingBox maximums

### ISSUE THREAD

**Issue by galactic-src** [mrc-ide/covid-sim#335]
When the SpatialBoundingBox is compared to a point's coordinates, as I understand it, they are compared less than or equal to a lower limit and strictly less than an upper limit. However, to facilitate that, it adds a little delta (1e-6) to create the upper bound when deriving it from density data.

Would the world be simpler if the upper bound was compared less than or equal to and it didn't need to add the delta to support the strict less than?

Happy to look at this if it's considered helpful.

**Comment by weshinsley** [comment]
The 1e-6 is just to overcome comparing two floating point numbers, when the final target is an integer. Quite common to see this, as a floating point x <= y doesn't always do what you want.
