### ISSUE TITLE
"make test" fails on some of our machines

### ISSUE THREAD

**Issue by sje30** [mrc-ide/covid-sim#342]
hi,
I can get CovidSim to compile on some machines, on others, like our HPC head node, "make test" fails.  See the log at:

https://gist.github.com/sje30/55369be411791b72e585687049d5de8f

CC: @draenog

**Comment by weshinsley** [comment]
Hi @sje30 - could you give me any info on the compiler/architecture of your head node (or something the tests have failed on?) - we can't reproduce that with master on any of our current configurations...

**Comment by sje30** [comment]
Does `lscpu` tell you much about this machine?  what other command shall I run to give you info?

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       46 bits physical, 48 bits virtual
CPU(s):              48
On-line CPU(s) list: 0-47
Thread(s) per core:  2
Core(s) per socket:  12
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz
Stepping:            4
CPU MHz:             2300.000
CPU max MHz:         3200.0000
CPU min MHz:         1000.0000
BogoMIPS:            4600.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            16896K
NUMA node0 CPU(s):   0-11,24-35
NUMA node1 CPU(s):   12-23,36-47
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin mba tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_pkg_req pku ospke

```

**Comment by weshinsley** [comment]
That looks fine - what about g++ --version ?

You've also got a system-specific error in the logs - not sure whether that is contributing anything...

Unable to create directory /nfs/st01/hpc-cbi-sje30/sje30/codecheck-report9/covid-sim/build-fawcett/tests/uk-output/st-results-noint.ge

**Comment by sje30** [comment]
I believe the tests failed on generating different md5sums.  My colleague Kacper @draenog might be able to provide more info.

**Comment by sje30** [comment]
```
g++ --version
g++ (GCC) 7.3.0

```

**Comment by weshinsley** [comment]
Thanks -  nothing obvious I can spot so far... will take a deeper look...

**Comment by draenog** [comment]
So it seems to depend on number of threads. On all machines I have tried so far  test inttest-us-based fails with OMP_NUM_THREADS=1 and succeeds with OMP_NUM_THREADS=2.

**Comment by weshinsley** [comment]
Actually, if I'm reading the logs correctly, I think your multi-threaded test runs are producing the same hash as your single-threaded, which should not be the case; because should have two RNGs (one for each thread) on the multi-threaded test, and the hash should be different...

**Comment by weshinsley** [comment]
@draenog - there's your problem - when you set OMP_NUM_THREADS=1, the multi-threaded regression tests won't be able to run normally, since they'll only detect one core.
