### ISSUE TITLE
Failed to build from source on openSUSE - make install?

### ISSUE THREAD

**Issue by kevinsmia1939** [mrc-ide/covid-sim#349]
Hello,
I am trying to build covid-sim from source on openSUSE Tumbleweed.
I am using cmake and gcc-c++ on openSUSE's Build Service. 
The are some warning, but what I think made it failed is  
`ERR_CRITICAL("Too many input lines while reading density file\n")`

Dependecies I include for building are
```
BuildRequires:  cmake
BuildRequires:  gcc-c++
BuildRequires:  libgomp1
BuildRequires:  libomp10-devel
```
The flags I use are
```
%cmake -DUSE_OPENMP:BOOL=OFF \
              -DCMAKE_INSTALL_PREFIX:PATH=/usr
```

Repository: https://build.opensuse.org/package/show/home:andythe_great/covid-sim
Full error log here: https://build.opensuse.org/build/home:andythe_great/openSUSE_Tumbleweed/x86_64/covid-sim/_log

```
[   92s] /home/abuild/rpmbuild/BUILD/covid-sim-0.13.0/src/SetupModel.cpp: In function 'void SetupModel(char*, char*, char*, char*)':
[   92s] /home/abuild/rpmbuild/BUILD/covid-sim-0.13.0/src/SetupModel.cpp:72:15: warning: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Wsign-compare]
[   92s]    72 |     if (index == P.BinFileLen) ERR_CRITICAL("Too many input lines while reading density file\n");
[   92s]       |         ~~~~~~^~~~~~~~~~~~~~~
[   92s] /home/abuild/rpmbuild/BUILD/covid-sim-0.13.0/src/SetupModel.cpp:101:14: warning: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Wsign-compare]
[   92s]   101 |    if (index != P.BinFileLen) ERR_CRITICAL("Too few input lines while reading density file\n");
[   92s]       |        ~~~~~~^~~~~~~~~~~~~~~
```

Thanks

**Comment by weshinsley** [comment]
Thanks for the report - those two things above are just warnings (which we can/should fix), but not the reason your build is failing. 

I'm not familiar with the way you're building it - but I think from the logs, your build process is expecting there to be a "make install" target which we don't have; current cmake just makes the executable in ./build/src. (See https://build.opensuse.org/package/show/home:andythe_great/covid-sim - the build process should be really easy)

It also looks from the flags above, and from the logs like you're disabling OpenMP; all the other warnings in your build are coming from that, as the #pragma omp lines don't get treated correctly.

**Comment by zebmason** [comment]
@kevinsmia1939 You might want to look at the build instructions for the [OpenSuSE container](https://github.com/mrc-ide/covid-sim/blob/master/.github/workflows/linux_distribution_check.yml)

**Comment by kevinsmia1939** [comment]
I have update the build flag to use OpenMP, but the build still fail.
```
%cmake -DUSE_OPENMP:BOOL=ON \
       -DOpenMP_CXX_FLAGS:STRING="%{optflags} -fopenmp" \
       -DOpenMP_C_FLAGS:STRING="%{optflags} -fopenmp" \
       -DCMAKE_INSTALL_PREFIX:PATH=%{_prefix}
```

There are many warning and error, I think this result from OpenMP not properly recognised?
```
[   47s] /home/abuild/rpmbuild/BUILD/covid-sim-0.13.0/src/Update.cpp:1060: warning: ignoring #pragma omp critical [-Wunknown-pragmas]
[   47s]  1060 | #pragma omp critical (tot_treat)
[   47s]       | 
[   47s] /home/abuild/rpmbuild/BUILD/covid-sim-0.13.0/src/Update.cpp:1071: warning: ignoring #pragma omp atomic [-Wunknown-pragmas]
[   47s]  1071 | #pragma omp atomic
[   47s]       | 
[   47s] /home/abuild/rpmbuild/BUILD/covid-sim-0.13.0/src/Update.cpp:1107: warning: ignoring #pragma omp critical [-Wunknown-pragmas]
[   47s]  1107 | #pragma omp critical (closeplace)
[   47s]       | 
[   47s] /home/abuild/rpmbuild/BUILD/covid-sim-0.13.0/src/Update.cpp:1225: warning: ignoring #pragma omp critical [-Wunknown-pragmas]
[   47s]  1225 | #pragma omp critical (openplace)
```
 Full log: https://build.opensuse.org/package/live_build_log/home:andythe_great/covid-sim/openSUSE_Tumbleweed/x86_64

**Comment by kevinsmia1939** [comment]
Fix the the issue.
Use install -Dm0755 instead of %cmake_install
https://forums.opensuse.org/showthread.php/540313-How-to-enable-OpenMP-on-cmake-gcc-(covid-sim)
