### ISSUE TITLE
More info on place types and age groups

### ISSUE THREAD

**Issue by kevinminors** [mrc-ide/covid-sim#371]
Hello all, 

Thanks for the great work. 

I am trying to build new parameter files and I can't figure out from the documentation or the code what the place types, the associated max/min age groups, and age groups 1-3 represent. 

I think it's somehow related to primary school, secondary school, working, and maybe university but I can't quite figure out how the numbers are split exactly. 

What are the 4 place types in the UK admin file? What are the differences between age groups 1-3? How are these related in the [Minimum age for age group 2 in place types] type parameters? Forgive me if I've missed the info somewhere. Thanks!

**Comment by insidedctm** [comment]
I'm not sure if this helps but this [Pull Request](https://github.com/derekwinton/covid-sim/blob/patch-2/docs/parameters-description.md) includes some detail on parameters.

**Comment by weshinsley** [comment]
More docs are on the way about this, and it is a bit fiddly; there are ways this could be simpler to express. But essentially: 

Age groups 1-3 are arbitrary in themselves; they just allow you to assign people from three separate age groups to the same place-type. Everyone is assigned to at most 1 place type. So going through the UK example, looking at the first column of the age groups (first place type):-

Age 5-11: Proportion 0.976 of ages 5-11 will be assigned to the first place type
Age 3-5: Proportion 1 (all 3-5 year olds)
Age 21-65: Proportion 0.00529...

Similar for the other place types. Place type 1 for UK is nursery/primary schools (3-5 yr olds, 5-11 yr olds, and teachers). The other place types for UK will be seconday, university, and workplace, as you saw, but that is just implied by the ages. You can configure more (or fewer) place types, with different ages, representing different place types. It depends what you think is most crucial to model for a particular country. Proportions for any given age should sum to <=1.

**Comment by kevinminors** [comment]
Thanks both!

@weshinsley That's really clear. Thank you. I understand now.
