### ISSUE TITLE
Question about compilation using GCC 7

### ISSUE THREAD

**Issue by mwoodbri** [mrc-ide/covid-sim#378]
First of all apologies: I'm not a C++ developer!

I've been trying to ensure that releases of covid-sim run on Imperial College's HPC system, following the practices we typically recommend to our users (i.e. using modules + conda).

Version 0.13 was fine, but 0.14 introduced [this change](https://github.com/mrc-ide/covid-sim/blob/master/src/SetupModel.cpp#L2484), which (apart from being strangely indented) seems to require a newer C++ feature(?) and causes a compilation error with the version of GCC (7.3) in my conda environment (which just contains `python=3` and `r-sp`):

```
In file included from /rdsgpfs/general/user/mwoodbri/home/tmp/covid-sim/src/SetupModel.cpp:7:0:
/rdsgpfs/general/user/mwoodbri/home/tmp/covid-sim/src/SetupModel.cpp: In function 'void LoadPeopleToPlaces(char*)':
/rdsgpfs/general/user/mwoodbri/home/tmp/covid-sim/src/SetupModel.cpp:2479:73: error: expected ')' before 'PRId32'
     ERR_CRITICAL_FMT("Random number seeds do not match saved values: %" PRId32 " != %" PRId32 " || %" PRId32 " != %" PRId32 "\n", s1, P.setupSeed1, s2, P.setupSeed2);
```

I would have expected `set(CMAKE_CXX_STANDARD 14)` to be sufficient as specified [here](https://github.com/mrc-ide/covid-sim/blob/master/CMakeLists.txt#L53). However, for it to work I also need to add `set(CMAKE_CXX_FLAGS "-D__STDC_FORMAT_MACROS")`.

Three questions:
- Should this be necessary for GCC 7?
- If so, is there a cleaner way of doing it?
- Would you consider including such a change?

Any advice much appreciated.

**Comment by weshinsley** [comment]
I can compile master fine in G++ 7.3.1 on "metal" CentOS by just running...
mkdir build
cd build
cmake ../covid-sim
cmake --build .

I wonder whether something obnoxious is happening with the %" or the "\n" when in a conda environment?

**Comment by mwoodbri** [comment]
Confirmed (inexplicably so far) not to be an issue with exact same version of GCC (7.3.0) outside of Conda so closing this. Thanks Wes - and apologies for the distraction.

**Comment by weshinsley** [comment]
(Long delay...) YES - above is a fix - or for a code fix,
`#define __STDC_FORMAT_MACROS 1` 
before you 
`#include <inttypes.h>`

**Comment by mwoodbri** [comment]
@weshinsley Yep, just checked and `export CXXFLAGS=...` no longer necessary to avoid compilation errors in Conda. Many thanks for the update.
