### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [mrc-ide/covid-sim#380]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/SLHGHD
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by weshinsley** [comment]
Thanks for including the dataset and for letting us know - but as you'll see from this repo, afraid we just don't have any time to commit to maintaining other external sites. It would be better if external sites could refer to here as the source of truth on our data.
