### ISSUE TITLE
You can't multiply two vectors to get another vector

### ISSUE THREAD

**Issue by zebmason** [mrc-ide/covid-sim#424]
https://github.com/mrc-ide/covid-sim/blob/f6d40d605feeaac0d18ae256875808df42eecf92/src/Geometry/Vector2.cpp#L5

This has no basis in vector algebra so is dangerous

**Comment by insidedctm** [comment]
The operation results in both components of the Vector2 being squared. I'd guess this is a precursor to doing something like a distance calculation. How is it used in the main code? This should either be renamed or maybe a change to the interface to make it more obvious what the Vector2 operation is actually being used to do.

**Comment by zebmason** [comment]
The Vector2 class is used to represent both a vector and a diagonal matrix hence the mixed algebra
