### ISSUE TITLE
Fail early on regression tests?

### ISSUE THREAD

**Issue by zebmason** [mrc-ide/covid-sim#452]
The unit and regression tests have just been split from one another. If I remember rightly this means that ctest is always used to run the tests and that it is possible to get the tests to stop on the first failed test.

If there is any interest I'll get the regression tests to stop on the first failed test - the unit tests will all run pass or fail.

**Comment by weshinsley** [comment]
Yes, I think that would be good - I was wondering if that might be possible, since unit tests are likely to fail (or indeed, succeed) faster than the regression tests...
