### ISSUE TITLE
Uninitialized variable 'ModelValue' used. CovidSim.cpp 5412

### ISSUE THREAD

**Issue by SecNotice** [mrc-ide/covid-sim#464]
V614 [CWE-457] Uninitialized variable 'ModelValue' used. [CovidSim.cpp 5412](https://github.com/mrc-ide/covid-sim/blob/a8273aa8b27e8e38d1ad473ccae704805ecbc4c5/src/CovidSim.cpp#L5412)

```
double ModelValue;
for (int k = offset; k < day; k++)
{
  double prob_seroconvert = ....;
  ModelValue += c * TimeSeries[k - offset].incI * prob_seroconvert;
}
```

See https://translate.google.com/translate?sl=ru&tl=en&u=https://www.viva64.com/ru/b/0796/ for more information.

**Comment by AndreyKarpov** [comment]
The author's article in English: [COVID-19 Research and Uninitialized Variable](https://www.viva64.com/en/b/0796/).

**Comment by krook1024** [comment]
Do you think #465 would solve this issue?

**Comment by weshinsley** [comment]
Merged - thank you. It's in some new code we're not yet using, and it's a missed simple compiler warning actually - it doesn't really demonstrate the power of PVS, re the first post. When we eventually fix all the tiny "fscanf return value ignored" style warnings leftover, we may treat warnings as errors in the future to spot these sort of things earlier.

**Comment by AndreyKarpov** [comment]
I started to compose my response to this comment. But I got carried away and wrote a small post that I published in our blog :). You can find it here: [Power of PVS-Studio](https://www.viva64.com/en/b/0802/).
