### ISSUE TITLE
Columns in age-specific output

### ISSUE THREAD

**Issue by klpn** [mrc-ide/covid-sim#467]
If age-specific output is created by setting `OutputAge` to `1`, the column `C[age]` in the generated `*avNE.age.xls`, which, according to [the documentation](https://github.com/mrc-ide/covid-sim/blob/master/docs/inputs-and-outputs.md#nameavneagexls), should contain critical cases for the age group, actually contains cases (seems to be due to [output generation](https://github.com/mrc-ide/covid-sim/blob/master/src/CovidSim.cpp#L3669), and [update of incCa](https://github.com/mrc-ide/covid-sim/blob/master/src/CovidSim.cpp#L4974)).

**Comment by dlaydon** [comment]
Thanks for spotting. You're right, documentation should indeed state that .incCa is the incidence of cases (i.e. symptomatic). https://github.com/mrc-ide/covid-sim/pull/468 resolves this. Cheers!
