### ISSUE TITLE
Unclear code (unnecessary braces) in Update.cpp: DoInfect

### ISSUE THREAD

**Issue by AndreyKarpov** [mrc-ide/covid-sim#482]
Hello. We accidentally found a new bug.

https://github.com/mrc-ide/covid-sim/blob/a5d2a0b981aca828f20938cea249ba66b4d1c682/src/Update.cpp#L123-L124

Details: [Example of How New Diagnostics Appear in PVS-Studio](https://www.viva64.com/en/b/0814/).

**Comment by weshinsley** [comment]
Good spot - I think that's just redundent bracketing - not a bug.

**Comment by weshinsley** [comment]
Removed unnecessary braces iin PR #483
