### ISSUE TITLE
PVS-Studio: V779 Unreachable code detected. It is possible that an error is present. CovidSim.cpp 675

### ISSUE THREAD

**Issue by AndreyKarpov** [mrc-ide/covid-sim#484]
Hello. New issue: [How PVS-Studio Prevents Rash Code Changes](https://www.viva64.com/en/b/0817/).

**Comment by weshinsley** [comment]
Thanks for pointing out - again, no impact or change in behaviour - just 68k of heap that could be freed.

**Comment by weshinsley** [comment]
Merged in PR #485
