### ISSUE TITLE
Redundant line

### ISSUE THREAD

**Issue by WeiqunZhang** [mrc-ide/covid-sim#63]
https://github.com/mrc-ide/covid-19-spatial-sim/blob/e698439cdfe3097f1849217e843270368b211116/src/SetupModel.cpp#L74

The assignment to `rn` seems redundant because of the `for` loop immediately following it.  But is the `for` loop meant to be skipped in case `feof` is reached?

**Comment by igfoo** [comment]
Thanks, this line was removed as part of #146.
