### ISSUE TITLE
Calloc zero size

### ISSUE THREAD

**Issue by WeiqunZhang** [mrc-ide/covid-sim#78]
https://github.com/mrc-ide/covid-19-spatial-sim/blob/0d474f113228482063373a284d6153a5483f6f39/src/SetupModel.cpp#L1916

In the line above, `Cells[i].n` might be zero.  In that case, the behavior of `calloc` is implementation dependent.  It might return a nullptr.  (https://linux.die.net/man/3/calloc)  This may cause the assertion to fail.

**Comment by weshinsley** [comment]
I think this is fixed with the work in Memory.cpp.
